import { apiError, apiServerError, apiSuccess } from "@/lib/api/api-response";
import { requireAuthAPI } from "@/lib/auth/auth-utils";
import { planService } from "@/server/application/services";
import { generateCustomizationOptions } from "@/server/application/use-cases/generate-customization-options/generateCustomizationOptions";
import { AppError } from "@/server/domain/errors";

/**
 * POST /api/customize/options
 *
 * Accepts a JSON body with:
 *  - `car`: vehicle name/model (string)
 *  - `categories`: customization categories (string[])
 *
 * Returns vehicle-aware, ranked aftermarket options per category, generated by
 * the WaveSpeed LLM.
 */
export async function POST(request: Request) {
  const { session, error } = await requireAuthAPI();
  if (error) return error;

  const userId = session?.user?.id;
  if (!userId) {
    return apiError("Unauthorized. Please sign in.", 401);
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return apiError("Expected a JSON request body", 400);
  }

  const { car, categories } = (body ?? {}) as {
    car?: unknown;
    categories?: unknown;
  };

  if (typeof car !== "string" || !car.trim()) {
    return apiError("A car name/model is required", 400);
  }

  if (!Array.isArray(categories)) {
    return apiError("Categories must be an array of strings", 400);
  }

  try {
    const planMode = await planService.getPlanModeForUserId(userId);
    const result = await generateCustomizationOptions({
      car,
      categories,
      planMode,
    });
    return apiSuccess(result, 201);
  } catch (err) {
    if (err instanceof AppError) {
      return apiError(err.message, err.statusCode, err.errorCode);
    }
    return apiServerError(err);
  }
}
